#global constants

#Pod window contents
WINDOW_POD="WINDOW_POD"
WINDOW_CM="WINDOW_CM"
WINDOW_SVC="WINDOW_SVC"
WINDOW_SECRET="WINDOW_SECRET"

WINDOW_LIST=[WINDOW_POD,WINDOW_CM,WINDOW_SVC,WINDOW_SECRET]
